# assets/<set>/*.png + assets/bg_classroom.png -> assets/sprites_data.js
#   window.SPRITE_SETS = { set: { key: dataURL } } ,  window.SPRITE_DATA = SPRITE_SETS.robot (구버전 호환),  window.BG_DATA
$dir = Split-Path $PSScriptRoot -Parent
$out = Join-Path $dir "assets\sprites_data.js"
$setParts = @()
foreach ($d in Get-ChildItem (Join-Path $dir "assets") -Directory | Where-Object { $_.Name -ne "src" }) {
    $parts = @()
    foreach ($png in Get-ChildItem (Join-Path $d.FullName "*.png")) {
        $b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($png.FullName))
        $key = [IO.Path]::GetFileNameWithoutExtension($png.Name)
        $parts += "    `"$key`": `"data:image/png;base64,$b64`""
    }
    if ($parts.Count) { $setParts += "  `"$($d.Name)`": {`n" + ($parts -join ",`n") + "`n  }" }
}
$bg = ""
$bgFile = Join-Path $dir "assets\bg_classroom.png"
if (Test-Path $bgFile) { $bg = "data:image/png;base64," + [Convert]::ToBase64String([IO.File]::ReadAllBytes($bgFile)) }
$js = "/* generated by tools/inject_sprites.ps1 — do not edit */`nwindow.SPRITE_SETS = {`n" + ($setParts -join ",`n") + "`n};`nwindow.SPRITE_DATA = window.SPRITE_SETS.robot || {};`nwindow.BG_DATA = `"$bg`";`n"
[IO.File]::WriteAllText($out, $js, (New-Object Text.UTF8Encoding $false))
Write-Output "wrote $out ($((Get-Item $out).Length) bytes, sets=$($setParts.Count), bg=$([bool]$bg))"
